title: Bovenzo | Tecnologia, Startups e MVP's 
subtitle: Descomplicando soluções tecnológicas na criação de MVP e criação de produto de tecnologia
description: Falo sobre minhas experiências e aprendizados ao longo da minha carreira de desenvolvedor e sobre o que vi dando certo e errado em pequenas e grandes corporações
keywords: startup, tecnologia, inovação, MVP
author: Bovenzo, Alisson Desandro
language: pt-BR
timezone: 'America/Sao_Paulo'
url: https://alissonbovenzo.github.io
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: artigos
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: 'Bovenzo | :title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: DD-MM-YYYY
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: 
  - ./source/assets
exclude: null
ignore: null
theme: icarus
deploy:
  type: git
  repo: https://github.com/alissonbovenzo/alissonbovenzo.github.io.git
  branch: [gh-pages]

feed:
  type: 
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml